"""Create users table

Revision ID: 9f87bc4287fb
Revises: 
Create Date: 2025-11-17 11:05:57.015475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f87bc4287fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('HistoryId', sa.Integer(), nullable=False),
    sa.Column('ImageUrl', sa.String(), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('UID', sa.String(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('HistoryId')
    )
    op.create_index(op.f('ix_history_HistoryId'), 'history', ['HistoryId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_HistoryId'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
